# Generated by Django 6.0 on 2025-12-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=150)),
                ("session_package_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("weight_kg", models.DecimalField(decimal_places=3, max_digits=10)),
                ("content_price_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_price_rub",
                    models.DecimalField(
                        blank=True, db_index=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="packages.packagetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_key", "session_package_id"),
                        name="unique_session_package_id",
                    )
                ],
            },
        ),
    ]
