# Generated by Django 6.0 on 2025-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="company_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
